stages:
  train:
    cmd: python main.py -c params.yaml
    deps:
    - cifar_simclr_resnet
    - data
    params:
    - params.yaml:
    outs:
    - dvclive/models
    metrics:
    - dvclive/metrics.json:
        cache: false
    plots:
    - dvclive/plots:
        cache: false
