# pytorch_lightning==1.9.4
trainer:
  logger: dvclive.lightning.DVCLiveLogger
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: dvclive/models
  max_epochs: 100
  accelerator: gpu
model:
  pretrained: true
data:
  train_size: 0.1
